TP-26139 Label Resolution Option: Update API docs
Scurri/apidocs pull request #22
Opened 2022-08-07 19:05 UTC by paweljaworowski-sc

Label Resolution Option: Update API docs
https://scurri.tpondemand.com/entity/26139-label-resolution-option-update-api-docs

As Ops, I would like the API docs to be updated with the new label resolution option so that customers are aware that we have this feature available. 

**Acceptance Criteria**
- In the API docs available online, add the following updates: 
Next text to be added underneath the paragraph:
'The resulting documents are base64-encoded and they can be either in PDF format or in PNG. In the former case, there is one PDF returned with multiple labels concatenated in a single document (one label per page). In the latter case, we cannot concatenate PNG files together, so a ZIP file is returned instead that contains all files.' 
- New text 'Labels can be configured as 230 or 300 DPI resolution. It's also possible to specify the required label resolution per request. To enable this feature, contact Scurri support. 

New and potential customers are aware of the option to specify the label resolution per request. 

2022-08-07 19:05 UTC, jgodoi commented
https://scurri.tpondemand.com/entity/26139

2022-08-08 08:20 UTC, brian-barba-hernandez requested changes

2022-08-08 08:20 UTC, brian-barba-hernandez commented on apiary.apib
> +Labels can be configured as 230 or 300 DPI resolution.
If this is only supported by `ZPL` we should say so here.

2022-08-08 08:31 UTC, paweljaworowski-sc commented on apiary.apib
> +Labels can be configured as 230 or 300 DPI resolution.
Hey @brian-barba-hernandez ,
Text was prepared by Kerrie, but you have right - I fixed that.

2022-08-08 09:35 UTC, brian-barba-hernandez approved these changes

2022-08-08 12:43 UTC, PaulGoodScurri approved these changes

2022-08-08 13:42 UTC, merged