TP-45536 More Custom Fields: Update API documentation
Scurri/apidocs pull request #33
Opened 2024-09-12 07:17 UTC by brian-barba-hernandez

More Custom Fields: Update API documentation
https://scurri.tpondemand.com/entity/45536-more-custom-fields-update-api-documentation

2024-09-12 09:25 UTC, jonathansweeney-sc approved these changes

2024-09-12 09:25 UTC, jonathansweeney-sc commented on apiary.apib
> +        + custom_field_5:(enum,optional) - A quinary custom field that takes a string or number to be used in the Scurri rules engine. It's only available for certain tiers. Contact support for more
Just a suggestion - maybe we should keep the language as simple as possible to give the impression of the API being easy to understand and use.

So we could change these to "a second custom field...", "a third custom field...", "a fourth...", "a fifth..." instead of "secondary", "tertiary", "quaternary", "quinary" (I did not even know that last one :sweat_smile:)

2024-09-12 09:56 UTC, brian-barba-hernandez commented on apiary.apib
> +        + custom_field_5:(enum,optional) - A quinary custom field that takes a string or number to be used in the Scurri rules engine. It's only available for certain tiers. Contact support for more
@jonathansweeney-sc I had to google them :joy:

2024-10-23 16:33 UTC, dmitrynedbaylo-sc requested changes

2024-10-23 16:33 UTC, dmitrynedbaylo-sc commented on apiary.apib
> +        + custom_field_5:(enum,optional) - A quinary custom field that takes a string or number to be used in the Scurri rules engine. It's only available for certain tiers. Contact support for more
@brian-barba-hernandez I don't even know how to pronounce them. Let's update and use simple language.

2024-10-24 13:40 UTC, jonathansweeney-sc approved these changes

2024-10-24 15:47 UTC, dmitrynedbaylo-sc approved these changes

2024-10-25 08:07 UTC, merged